CheckInternalHash: false
CheckInternal: true
IgnoreDirectoryMissingTrailingSlash: true
CheckScripts: false
IgnoreAltMissing: true
IgnoreURLs:
  - "emoflon.org"
HTTPHeaders:
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
  "accept-encoding": "deflate"
