baseURL: https://emoflon.org
languageCode: en-us
defaultContentLanguage: en
title: eMoflon Project Site
theme: cayman-hugo-theme

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

params:
  # Header text, can be markdown
  project_name: "![](/img/eMoflonLogoWithTex_semitransparent_300px.png)"
  project_tagline: "**eMoflon** is a tool suite for Model-Driven Engineering (MDE) that provides a range of visual and formal languages for (meta)modelling and model management."
  project_tagline_sub: "eMoflon currently consists of the following tools, which all share a common foundation based on graph pattern matching and graph transformations:"

  # Theme customizations by us
  frontpage_text: ""

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02

  # Footer text, can be markdown
  footer: Copyright 2012-2022 eMoflon Developer Team &bull; Built with [Hugo](https://gohugo.io/) &bull; [Theme](https://github.com/zwbetz-gh/cayman-hugo-theme) &bull; [Legal Notice](https://www.es.tu-darmstadt.de/impressum) &bull; [Privacy Policy](https://www.es.tu-darmstadt.de/es/datenschutzerklaerung).

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: News
      url: /
      weight: 1
    - name: "eMoflon::IBeX"
      url: /ibex/
      weight: 2
    - name: "eMoflon::Neo"
      url: /neo/
      weight: 3
    - name: "In Action"
      url: /action/
      weight: 4
    - name: "Development"
      url: /dev/
      weight: 5
    - name: "Download"
      url: /download/
      weight: 6
#    - name: RSS
#      url: /index.xml
#      weight: 7
